---
version: "3.7"

services:
  install_site:
    build: install_site
    ports:
      - "80:80"
    environment:
      - BASE_URL=$BASE_URL
      - EMAIL=$EMAIL
    volumes:
      - ./nginx.conf:/web/nextcloud.conf
      - sites-availables:/sites-availables/
      - certs:/etc/letsencrypt/

  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

  gitea:
    image: gitea/gitea:1.17
    restart: unless-stopped
    volumes:
      - data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=$PUID
      - USER_GID=$PGID
      - POSTGRES_HOST=db
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=$POSTGRES_DB
      - GITEA__database__USER=$POSTGRES_USER
      - GITEA__database__PASSWD=$POSTGRES_PASSWORD
    networks:
      - default
      - selfhost
    depends_on:
      - db

volumes:
  data:
  sites-availables:
    external: true
  certs:
    external: true

networks:
  default:
  selfhost:
    external: true
